### Variables
@baseUrl = http://localhost:8080
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGktcG9zdHVwIiwic3ViIjoiYWI5MWVhYjAtYjI0YS00ZmQ3LTk2YmQtMWQyZThiNzYzMWMxIiwiZXhwIjoxNzQxNDY4MDczfQ.NesZLXJCc4ZQTkSu3IhkFQrrI2lDDvCkfc2lHGqD24Y

### Create user
POST http://localhost:8080/users
Content-Type: application/json

{
  "email": "user0@postup.app",
  "username": "user0",
  "firstName": "User",
  "lastName": "0",
  "password": "123"
}

### Login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "user0@postup.app",
  "password": "123"
}

### Get profile
GET http://localhost:8080/users/profile
Content-Type: application/json
Authorization: Bearer {{token}}

### Create post
POST http://localhost:8080/posts
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "content": "hello",
  "parentPostId": "f16f0c70-ef66-4bb3-b0da-5332c2487282"
}

### Get my posts
GET http://localhost:8080/posts/my
Content-Type: application/json
Authorization: Bearer {{token}}

### Get post by id
GET http://localhost:8080/posts/details/f16f0c70-ef66-4bb3-b0da-5332c2487282
Content-Type: application/json
Authorization: Bearer {{token}}
